name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync

    - name: Install system dependencies for CLI connectors
      run: |
        # Install PostgreSQL client
        sudo apt-get update
        sudo apt-get install -y postgresql-client

        # Install ClickHouse client
        sudo apt-get install -y apt-transport-https ca-certificates curl gnupg
        curl -fsSL 'https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key' | sudo gpg --dearmor -o /usr/share/keyrings/clickhouse-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg] https://packages.clickhouse.com/deb stable main" | sudo tee /etc/apt/sources.list.d/clickhouse.list
        sudo apt-get update
        sudo apt-get install -y clickhouse-client

        # Install sshpass for SSH password authentication tests
        sudo apt-get install -y sshpass

    - name: Install Docker Compose plugin
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose-plugin

    - name: Run tests
      run: |
        # Run the test script
        ./run_tests.sh
      env:
        PYTHONUNBUFFERED: 1

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          .pytest_cache/
          test-results/
        if-no-files-found: ignore

    - name: Clean up
      if: always()
      run: |
        docker-compose --profile test down
